name: Bug report for existing awesome-gee-catalog dataset
description: Create a bug report about existing dataset in catalog
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - samapriya, valpasq, edtrochim
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: input
    id: Dataset-URL
    attributes:
      label: Provide Dataset Link
      description: Provide a link to the existing dataset page ex. https://gee-community-catalog.org/projects/geomorpho90/
    validations:
      required: true
  - type: textarea
    id: Clear_and_concise_description_about_the_bug
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      value: "Describe the bug"
    validations:
      required: true
  - type: textarea
    id: additional_info
    attributes:
      label: Relevant additional information
      description: If applicable, add screenshots/error messages/logs to help explain your problem.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://gee-community-catalog.org/code_of_conduct/)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
